INSERT INTO USER (ID, NAME, BIRTH_DATE) VALUES (1001,  'India', SYSDATE);
INSERT INTO USER (ID, NAME, BIRTH_DATE) VALUES (1002,'Brazil', SYSDATE);
INSERT INTO USER (ID, NAME, BIRTH_DATE) VALUES (1003, 'USA', SYSDATE);
INSERT INTO USER (ID, NAME, BIRTH_DATE) VALUES (1004, 'Italy', SYSDATE);
INSERT INTO POST (ID, DESCRIPTION, USER_ID) VALUES (1101, 'First Post', 1001 );
INSERT INTO POST (ID, DESCRIPTION, USER_ID) VALUES (1102,'Second Post', 1001);
INSERT INTO POST (ID, DESCRIPTION, USER_ID) VALUES (1103, 'Third Post', 1002);
INSERT INTO POST (ID, DESCRIPTION, USER_ID) VALUES (1104, 'Fourth Post', 1002);